@ControllerAPI_HostAddress = http://localhost:5197/api

GET {{ControllerAPI_HostAddress}}/User
Accept: application/json

###

GET {{ControllerAPI_HostAddress}}/User/2
Accept: application/json

###

POST  {{ControllerAPI_HostAddress}}/User
Content-Type:  application/json
Accept: application/json

{
    "id": 3,
    "username": "Dee",
    "email": "test3@gmail.com",
    "fullname": "Dee Jing"
}

###
PUT {{ControllerAPI_HostAddress}}/User/3
Content-Type:  application/json

{
    "id": 3,
    "username": "Dee22",
    "email": "test322@gmail.com",
    "fullname": "Dee2 Jing3"
}

###
DELETE {{ControllerAPI_HostAddress}}/User/3
Accept: application/json